import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const worker=(await import(pathToFileURL(path.resolve('dist/server/index.js')))).default;
const types={'.js':'application/javascript','.css':'text/css','.html':'text/html','.rsc':'text/x-component','.svg':'image/svg+xml','.png':'image/png','.woff':'font/woff','.woff2':'font/woff2','.webp':'image/webp','.jpg':'image/jpeg','.jpeg':'image/jpeg','.ico':'image/x-icon','.mp4':'video/mp4'};
const base=path.resolve('dist/client');
const env={ASSETS:{async fetch(request){const u=new URL(request.url);const file=path.resolve(base,'.'+decodeURIComponent(u.pathname));if(!file.startsWith(base+path.sep))return new Response('Not found',{status:404});try{const body=await fs.readFile(file);return new Response(body,{headers:{'Content-Type':types[path.extname(file)]||'application/octet-stream'}});}catch{return new Response('Not found',{status:404});}}}};
const port=Number(process.env.PORT||3000);
http.createServer(async(req,res)=>{try{const response=await worker.fetch(new Request('http://localhost:'+port+req.url,{headers:req.headers}),env);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}catch(e){console.error(e);res.writeHead(500);res.end('Server error');}}).listen(port,'0.0.0.0',()=>console.log('Local: http://localhost:'+port));
